folders:
  scripts: "scripts"
  output: "output"
  containers: "containers"
  sentinel: "sentinel"

files:
  surge_input: "config/surge_input.txt"
  pydev_sentinel: "sentinel/pydev_image.sentinel"
  surge_sentinel: "sentinel/surge_image.sentinel"
  sql_sentinel: "sentinel/sql_sentinel"
  sql_running_sentinel: "sentinel/sql_running_sentinel"
  network_sentinel: "sentinel/network_sentinel"
  schema_created_sentinel: "sentinel/schema_created.sentinel"

sql:
  root_password: "swoosh"
  database: "leads"

debug: True  # Set to true during development to enable cleanup
